### ISSUE TITLE
clarify some information if you're looking for contributions

### ISSUE THREAD

**Issue by joeclark-phd** [lorgam/spacecolon#1]
Hi. I'm interested in any game based on _Colonization_, and might like to contribute.  There's not enough information to do so, yet.  If you'd like contributions, I'd recommend adding some documentation on the design goals as well as the technology stack.

- **Design**: What will the game be all about?  What do you want it to look like?
- **Technology**: I can see that it's Javascript, but what framework(s) or build tool(s) does it use? Any guidelines on code structure?

**Comment by lorgam** [comment]
Hello Joseph.

I'm not very active in this project at the moment but I'll try to add the documentation ASAP.

**Comment by lorgam** [comment]
I've updated the readme and the wiki with the recommended documentation.
